### PR TITLE
Call endpoint modifications for Rosetta-cusd

### PR DESCRIPTION
**Pull request by eelanagaraj**
# Description
This PR includes changes necessary for the `rosetta-cusd` module, which relies on the `/call` endpoint. The main changes:

- Register `StableToken.balanceOf` method (note: did **not** add this to the `ArgBuilder` interface as I wasn't sure if that should be limited to core CELO functionality--happy to add this to that interface if that makes sense @yorhodes)
- Adds logic to use optional arg `callParams.BlockNumber` (if present) to pull the relevant blockHeader, and pass this in to the underlying `CallData` (which in turn passes this to the ethClient's `CallContract`). If no number is passed in, it pulls the node's current tip.
- Adds `BlockIdentifier` to the `/call` `celo_call` method result and introduces a type for this: `CallResult`; introduce a result type for the `celo_logs` result as well `CallLogsResult`.

The first two changes should not be breaking, but the last change could potentially be; tagging @arjun-io for visibility. If so, we can make this part of a bigger breaking 1.0.0 release and keep it off master for now.

### CODE REVIEW

**Comment by arjun-io** [comment]
Thanks for the heads up, this won't be a breaking change for us so feel free to merge when it's ready

**Review by yorhodes — APPROVED** [review]
`StableToken.Transfer` is what should be added to `ArgBuilder`

**Comment by eelanagaraj** [comment]
@yorhodes ok awesome thanks, so just to check my understanding then: argbuilder should include all functionality relevant to constructing transactions with other contracts?

**Comment by yorhodes** [comment]
> @yorhodes ok awesome thanks, so just to check my understanding then: argbuilder should include all functionality relevant to constructing transactions with other contracts?

Until the construction API is implemented, in which case the argbuilder interface itself shouldn't be necessary

**Pull request merged**
